-- BASELINE: documents the ACTUAL production schema as verified via direct psql introspection
-- on 2026-08-31/2026-09-01. This is NOT a migration to run against production — production
-- already has this shape. It exists so:
--   1. `supabase start` (local dev) creates a database that matches production, instead of the
--      old 20260823000001_init_saas.sql / 20260823000002_rls.sql shape, which was written against
--      an intended design that was never actually applied as-is (confirmed schema drift — see
--      TAXITIPS_STATUS.md "Schema drift" section for the full comparison).
--   2. Anyone reading the migration history going forward has a truthful starting point.
--
-- Do NOT edit this file to "fix" the schema — if production's shape needs to change, write a
-- new migration on top of this one (expand/migrate/contract), the same as any other change.
--
-- The old 20260823000001_init_saas.sql and 20260823000002_rls.sql migration files remain in
-- this directory for historical record but do not reflect what is actually running. They should
-- not be applied to a fresh database — this file supersedes them for that purpose.

create extension if not exists "pgcrypto";

-- profiles: extends auth.users, minimal shape (no email/status/deleted_at columns in prod)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text,
  is_platform_owner boolean,
  created_at timestamptz
);

-- companies: no trial_ends_at, billing_account_id, admin_notes, company_info_json,
-- join_code_updated_at in production. Has subscription_status (not in any prior migration file).
create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  org_number text,
  join_code text not null,
  seats integer not null default 1,
  status text not null default 'trial',
  watched_areas text[] not null default '{}',
  created_at timestamptz not null default now(),
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text not null default 'inactive',
  constraint companies_join_code_key unique (join_code)
);

create table if not exists public.company_members (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  user_id uuid not null,
  role text,
  status text,
  created_at timestamptz,
  constraint company_members_company_id_user_id_key unique (company_id, user_id)
);

-- devices: has `kind`, does not have last_seen_at (present in an earlier design doc, never applied)
create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  token text not null,
  label text not null,
  kind text not null,
  push_token text,
  notify_prefs jsonb not null default '{}'::jsonb,
  created_at timestamptz,
  constraint devices_token_key unique (token)
);

create table if not exists public.device_transfer_codes (
  code text primary key,
  device_id uuid not null,
  expires_at timestamptz not null
);

-- alerts: id is UUID in production (NOT text as in the old init_saas.sql migration file).
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  kind text,
  level text,
  title text,
  summary text,
  lat double precision,
  lon double precision,
  places jsonb,
  payload jsonb,
  updated_at timestamptz not null,
  h3_index text,
  start_time timestamptz,
  end_time timestamptz,
  demand_score integer,
  reasons text[],
  constraint alerts_demand_score_check check (demand_score >= 0 and demand_score <= 100)
);

create index if not exists idx_alerts_h3_index on public.alerts (h3_index);

-- alert_feedback.alert_id is uuid, correctly typed against alerts.id (uuid) -- no type
-- mismatch exists in production, despite the column type suggested by reading migration files
-- in isolation. RLS was OFF entirely until 20260901000002_alert_feedback_rls.sql.
create table if not exists public.alert_feedback (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid references public.alerts (id) on delete cascade,
  device_token text,
  result boolean,
  created_at timestamptz
);

-- Tables described in 20260823000001_init_saas.sql that DO NOT EXIST in production:
-- billing_accounts, subscriptions, tickets, app_config, processed_webhook_events.
-- Notably: the Stripe webhook handler (taxitips-api/worker/src/index.js) inserts into
-- processed_webhook_events for idempotency -- that insert would fail today if the worker
-- were deployed and a webhook arrived, since the table doesn't exist. This must be created
-- before the worker is deployed to production (see Phase 1.9 in the optimization plan).
create table if not exists public.processed_webhook_events (
  stripe_event_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now(),
  status text not null,
  error text
);
