# Generated by Django 6.1.1 on 2026-09-21 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_coupon', 'fleet_coupon_redemption', 'fleet_owner_invite'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_revoke_postgrest_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('days', models.IntegerField()),
                ('vehicle_limit', models.IntegerField(default=3)),
                ('max_redemptions', models.IntegerField(blank=True, null=True)),
                ('redemption_count', models.IntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_coupon',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trial',
            name='source',
            field=models.CharField(choices=[('self_signup', 'Självregistrering'), ('sales_invite', 'Säljarinbjudan'), ('sales', 'Säljare'), ('coupon', 'Kupong')], max_length=20),
        ),
        migrations.CreateModel(
            name='OwnerInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('email', models.TextField()),
                ('role', models.CharField(default='company_owner', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('consumed', 'Använd'), ('revoked', 'Återkallad')], default='pending', max_length=16)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_user', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_owner_invite',
                'indexes': [models.Index(fields=['email', 'status'], name='fleet_owner_email_a0a9d6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company_id', 'email'), name='fleet_one_pending_owner_invite')],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('effect', models.CharField(choices=[('temporary_access', 'Tillfällig åtkomst'), ('billing_deferred', 'Nästa debitering flyttad'), ('period_extended', 'Perioden förlängd')], max_length=20)),
                ('days', models.IntegerField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('redeemed_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='fleet.coupon')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.trial')),
            ],
            options={
                'db_table': 'fleet_coupon_redemption',
                'constraints': [models.UniqueConstraint(fields=('coupon', 'company_id'), name='fleet_coupon_once_per_company')],
            },
        ),
        # Samma spärr som 0003, för de nya tabellerna: ingen av dem får nås via
        # PostgREST, oavsett i vilken ordning Supabases migrationer har körts.
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
