# Generated by Django 6.1.1 on 2026-09-24 20:11

import uuid
from django.db import migrations, models


# Samma skäl som 0003/0004 (invariant 19): nya tabeller får inte nås via
# PostgREST, oavsett om Supabases default-privilegier är satta i miljön.
REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_known_account', 'fleet_account_block'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownAccount',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(db_index=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fleet_known_account',
            },
        ),
        migrations.CreateModel(
            name='AccountBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('company', 'Företag'), ('email', 'E-postadress'), ('user', 'Konto')], max_length=10)),
                ('value', models.CharField(max_length=320)),
                ('reason', models.TextField()),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_by', models.UUIDField(blank=True, null=True)),
                ('lift_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'fleet_account_block',
                'constraints': [models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True)), fields=('kind', 'value'), name='fleet_one_active_block')],
            },
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
