# Generated by Django 6.1.1 on 2026-09-26 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


# Samma skäl som 0003-0005 (invariant 19): supportchatten får inte nås via
# PostgREST, oavsett om Supabases default-privilegier är satta i miljön. All
# läsning går genom fleet/support_api.py, som kontrollerar vem som frågar.
REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_support_thread', 'fleet_support_message'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('requester_kind', models.CharField(choices=[('member', 'Konto'), ('device', 'Förartelefon')], max_length=10)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('requester_label', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Öppen'), ('closed', 'Avslutad')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_staff_message_at', models.DateTimeField(blank=True, null=True)),
                ('customer_read_at', models.DateTimeField(blank=True, null=True)),
                ('staff_read_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_support_thread',
                'indexes': [models.Index(fields=['status', '-last_message_at'], name='fleet_suppo_status_de1f50_idx'), models.Index(fields=['company_id'], name='fleet_suppo_company_36fc82_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('user_id',), name='fleet_support_one_thread_per_user'), models.UniqueConstraint(condition=models.Q(('device_id__isnull', False)), fields=('device_id',), name='fleet_support_one_thread_per_device'), models.CheckConstraint(condition=models.Q(models.Q(('device_id__isnull', True), ('requester_kind', 'member'), ('user_id__isnull', False)), models.Q(('device_id__isnull', False), ('requester_kind', 'device'), ('user_id__isnull', True)), _connector='OR'), name='fleet_support_requester_matches_kind')],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('customer', 'Användaren'), ('staff', 'Support')], max_length=10)),
                ('author_user_id', models.UUIDField(blank=True, null=True)),
                ('author_device_id', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fleet.supportthread')),
            ],
            options={
                'db_table': 'fleet_support_message',
                'indexes': [models.Index(fields=['thread', 'created_at'], name='fleet_suppo_thread__bb6ccf_idx')],
            },
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
