# Generated by Django 6.1.1 on 2026-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_support_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='registry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registry_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
