# Generated by Django 6.1.1 on 2026-09-29 13:28

from django.db import migrations, models

# Invariant 19: Djangos tabeller nås aldrig via PostgREST. Samma revoke som 0006.
REVOKE_NEW_TABLES = """
do $$
declare
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    if to_regclass('public.fleet_sales_followup') is not null then
      execute format('revoke all on table public.fleet_sales_followup from %I', r);
    end if;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_company_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFollowUp',
            fields=[
                ('company_id', models.UUIDField(primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('not_contacted', 'Inte kontaktad'), ('no_answer', 'Svarade inte'), ('call_back', 'Ring igen'), ('interested', 'Intresserad'), ('not_interested', 'Inte intresserad'), ('wrong_details', 'Fel uppgifter'), ('customer', 'Blev kund')], default='not_contacted', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('next_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('contact_attempts', models.IntegerField(default=0)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_sales_followup',
            },
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
