# Generated by Django 6.1.1 on 2026-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_sales_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='archived_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
