# Generated by Django 6.1.1 on 2026-09-30 17:52

import uuid
from django.db import migrations, models


# Invariant 19: Djangos tabeller nås aldrig via PostgREST. Klientaktiviteten
# bär IP-nät och telefonmodell per konto, felen bär feltexter -- ingetdera ska
# kunna läsas med Supabases anon- eller authenticated-nyckel. All läsning går
# genom fleet/admin_activity.py, som kräver personalroll.
REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_client_activity', 'fleet_client_error'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_company_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_kind', models.CharField(choices=[('user', 'Konto'), ('device', 'Telefon')], max_length=10)),
                ('subject_id', models.UUIDField()),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('app_build', models.CharField(blank=True, default='', max_length=16)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('device_model', models.CharField(blank=True, default='', max_length=64)),
                ('ip_prefix', models.CharField(blank=True, default='', max_length=48)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'db_table': 'fleet_client_activity',
                'indexes': [models.Index(fields=['company_id', '-last_seen_at'], name='fleet_clien_company_1c359b_idx'), models.Index(fields=['-last_seen_at'], name='fleet_clien_last_se_0451dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_kind', 'subject_id'), name='fleet_client_activity_one_per_subject')],
            },
        ),
        migrations.CreateModel(
            name='ClientError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_at', models.DateTimeField()),
                ('occurrences', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('app', 'Appen'), ('server', 'Servern')], max_length=10)),
                ('kind', models.CharField(choices=[('crash', 'Krasch'), ('flow', 'Flöde misslyckades'), ('server', 'Serverfel')], max_length=10)),
                ('flow', models.CharField(blank=True, default='', max_length=64)),
                ('error_type', models.CharField(blank=True, default='', max_length=80)),
                ('message', models.TextField(blank=True, default='')),
                ('stack', models.TextField(blank=True, default='')),
                ('fatal', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('app_build', models.CharField(blank=True, default='', max_length=16)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('device_model', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'fleet_client_error',
                'indexes': [models.Index(fields=['-last_at'], name='fleet_clien_last_at_8b35be_idx'), models.Index(fields=['company_id', '-last_at'], name='fleet_clien_company_d9f761_idx'), models.Index(fields=['created_at'], name='fleet_clien_created_c74e92_idx')],
            },
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
