# Generated by Django 6.1.1 on 2026-10-01 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


# Invariant 19: Djangos tabeller nås aldrig via PostgREST. Inbjudan bär
# förarens e-postadress och vilket bolag och vilken bil den gäller -- ingen av
# delarna ska kunna läsas med Supabases anon- eller authenticated-nyckel. All
# läsning och skrivning går genom fleet/api.py, som kräver MANAGE_DEVICES, och
# inlösen genom den verifierade inloggningen. Bara en ny tabell (expand); inget
# befintligt ändras.
REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_driver_invite'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_client_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('email', models.TextField()),
                ('label', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('consumed', 'Använd'), ('revoked', 'Återkallad')], default='pending', max_length=16)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('auth_user_id', models.UUIDField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.IntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_user', models.UUIDField(blank=True, null=True)),
                ('consumed_by_device', models.UUIDField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.UUIDField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.license')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_driver_invite',
                'indexes': [models.Index(fields=['email', 'status'], name='fleet_drive_email_cb3695_idx'), models.Index(fields=['company_id', '-created_at'], name='fleet_drive_company_1c45f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company_id', 'email'), name='fleet_one_pending_driver_invite')],
            },
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, reverse_sql=migrations.RunSQL.noop),
    ]
