# Generated by Django 6.1.1 on 2026-10-01 11:30

import uuid
from django.db import migrations, models


REVOKE_NEW_TABLES = """
do $$
declare
  t text;
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach t in array array['fleet_company_discount'] loop
      if to_regclass(format('public.%I', t)) is not null then
        execute format('revoke all on table public.%I from %I', t, r);
      end if;
    end loop;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0011_driver_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="planned_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CompanyDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent_bp", "Procent"), ("fixed_ore", "Fast belopp")],
                        max_length=16,
                    ),
                ),
                ("value", models.IntegerField()),
                ("description", models.TextField(blank=True, default="")),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fleet_company_discount",
            },
        ),
        migrations.AddConstraint(
            model_name="companydiscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company_id",),
                name="fleet_one_active_discount_per_company",
            ),
        ),
        migrations.RunSQL(REVOKE_NEW_TABLES, migrations.RunSQL.noop),
    ]
