# Generated by Django 6.1.1 on 2026-10-03 12:07
#
# Bara förarens engångskod (fleet/driver_login.py). makemigrations föreslog
# också indexnamn och ett choices-fält som väntat sedan tidigare; de hör inte
# hit och tas i en egen migrering.

import uuid
from django.db import migrations, models

# Kodhasharna ska aldrig nås via PostgREST (samma skäl som 0003 och 0019).
REVOKE = """
do $$
declare
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    if to_regclass('public.fleet_driver_login_code') is not null then
      execute format('revoke all on table public.fleet_driver_login_code from %I', r);
    end if;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_device_link_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_driver_login_code',
            },
        ),
        migrations.AddIndex(
            model_name='driverlogincode',
            index=models.Index(fields=['email', '-created_at'], name='fleet_drive_email_0bf991_idx'),
        ),
        migrations.RunSQL(sql=REVOKE, reverse_sql=migrations.RunSQL.noop),
    ]
