# Generated by Django 6.1.1 on 2026-10-03 14:38
#
# Expand: länbyten per bil och månad (fleet/county_changes.py) -- bytena och
# personalens extra byten. Bara nya tabeller. makemigrations föreslog också
# indexnamn och ett choices-fält som väntat sedan tidigare; de hör inte hit
# och tas i en egen migrering (samma som 0020).

import uuid

from django.db import migrations, models

# Aldrig via PostgREST (invariant 19, samma skäl som 0003 och 0019).
REVOKE = """
do $$
declare
  r text;
  tbl text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    foreach tbl in array array['fleet_county_change', 'fleet_county_change_grant'] loop
      if to_regclass('public.' || tbl) is not null then
        execute format('revoke all on table public.%I from %I', tbl, r);
      end if;
    end loop;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_driver_login_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_id', models.UUIDField()),
                ('company_id', models.UUIDField()),
                ('from_county', models.CharField(blank=True, default='', max_length=4)),
                ('to_county', models.CharField(blank=True, default='', max_length=4)),
                ('via', models.CharField(max_length=16)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fleet_county_change',
            },
        ),
        migrations.CreateModel(
            name='CountyChangeGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_id', models.UUIDField()),
                ('company_id', models.UUIDField()),
                ('month_key', models.CharField(max_length=7)),
                ('granted_by', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fleet_county_change_grant',
            },
        ),
        migrations.AddIndex(
            model_name='countychange',
            index=models.Index(fields=['license_id', '-created_at'], name='fleet_count_license_d5d410_idx'),
        ),
        migrations.AddIndex(
            model_name='countychangegrant',
            index=models.Index(fields=['license_id', 'month_key'], name='fleet_count_license_d0e113_idx'),
        ),
        migrations.RunSQL(sql=REVOKE, reverse_sql=migrations.RunSQL.noop),
    ]
