-- GENERATED FILE — do not edit directly.
-- Regenerate with taxitips-api/scripts/regen_all_migrations.sh after adding a migration.
-- Concatenation of taxitips-api/supabase/migrations/*.sql in filename order.
--
-- NOTE: the original 20260823000001_init_saas.sql and 20260823000002_rls.sql described a
-- schema design that was never actually applied to production as written (confirmed schema
-- drift, see TAXITIPS_STATUS.md). They were moved to supabase/migrations_historical/ and
-- are not part of this file. 20260828999999_baseline_actual_schema.sql documents the real
-- production shape and is the source of truth for standing up a fresh (e.g. local dev) DB.

-- ===== 20260828999999_baseline_actual_schema.sql =====
-- BASELINE: documents the ACTUAL production schema as verified via direct psql introspection
-- on 2026-08-31/2026-09-01. This is NOT a migration to run against production — production
-- already has this shape. It exists so:
--   1. `supabase start` (local dev) creates a database that matches production, instead of the
--      old 20260823000001_init_saas.sql / 20260823000002_rls.sql shape, which was written against
--      an intended design that was never actually applied as-is (confirmed schema drift — see
--      TAXITIPS_STATUS.md "Schema drift" section for the full comparison).
--   2. Anyone reading the migration history going forward has a truthful starting point.
--
-- Do NOT edit this file to "fix" the schema — if production's shape needs to change, write a
-- new migration on top of this one (expand/migrate/contract), the same as any other change.
--
-- The old 20260823000001_init_saas.sql and 20260823000002_rls.sql migration files remain in
-- this directory for historical record but do not reflect what is actually running. They should
-- not be applied to a fresh database — this file supersedes them for that purpose.

create extension if not exists "pgcrypto";

-- profiles: extends auth.users, minimal shape (no email/status/deleted_at columns in prod)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text,
  is_platform_owner boolean,
  created_at timestamptz
);

-- companies: no trial_ends_at, billing_account_id, admin_notes, company_info_json,
-- join_code_updated_at in production. Has subscription_status (not in any prior migration file).
create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  org_number text,
  join_code text not null,
  seats integer not null default 1,
  status text not null default 'trial',
  watched_areas text[] not null default '{}',
  created_at timestamptz not null default now(),
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text not null default 'inactive',
  constraint companies_join_code_key unique (join_code)
);

create table if not exists public.company_members (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  user_id uuid not null,
  role text,
  status text,
  created_at timestamptz,
  constraint company_members_company_id_user_id_key unique (company_id, user_id)
);

-- devices: has `kind`, does not have last_seen_at (present in an earlier design doc, never applied)
create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  token text not null,
  label text not null,
  kind text not null,
  push_token text,
  notify_prefs jsonb not null default '{}'::jsonb,
  created_at timestamptz,
  constraint devices_token_key unique (token)
);

create table if not exists public.device_transfer_codes (
  code text primary key,
  device_id uuid not null,
  expires_at timestamptz not null
);

-- alerts: id is UUID in production (NOT text as in the old init_saas.sql migration file).
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  kind text,
  level text,
  title text,
  summary text,
  lat double precision,
  lon double precision,
  places jsonb,
  payload jsonb,
  updated_at timestamptz not null,
  h3_index text,
  start_time timestamptz,
  end_time timestamptz,
  demand_score integer,
  reasons text[],
  constraint alerts_demand_score_check check (demand_score >= 0 and demand_score <= 100)
);

create index if not exists idx_alerts_h3_index on public.alerts (h3_index);

-- alert_feedback.alert_id is uuid, correctly typed against alerts.id (uuid) -- no type
-- mismatch exists in production, despite the column type suggested by reading migration files
-- in isolation. RLS was OFF entirely until 20260901000002_alert_feedback_rls.sql.
create table if not exists public.alert_feedback (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid references public.alerts (id) on delete cascade,
  device_token text,
  result boolean,
  created_at timestamptz
);

-- Tables described in 20260823000001_init_saas.sql that DO NOT EXIST in production:
-- billing_accounts, subscriptions, tickets, app_config, processed_webhook_events.
-- Notably: the Stripe webhook handler (taxitips-api/worker/src/index.js) inserts into
-- processed_webhook_events for idempotency -- that insert would fail today if the worker
-- were deployed and a webhook arrived, since the table doesn't exist. This must be created
-- before the worker is deployed to production (see Phase 1.9 in the optimization plan).
create table if not exists public.processed_webhook_events (
  stripe_event_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now(),
  status text not null,
  error text
);

-- ===== 20260829000000_rpc_functions.sql =====
-- RPC functions used by taxitips-app/lib/api_client.dart, verified against production's real
-- function bodies via direct psql introspection (2026-09-01) and cross-checked against
-- taxitips-app/supabase/001_schema.sql, the untracked bootstrap script that appears to have
-- actually been run against production (its header comment states the exact PGRST205 symptom
-- this repo's own migrations would otherwise have left unfixed). These were previously not
-- present in any tracked migration file, so `supabase start` never created them locally even
-- though the Flutter app depends on all of them (join_screen.dart, driver_screen.dart, signup).

create or replace function public.regenerate_join_code(p_company_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  if not exists (
    select 1 from public.company_members
    where company_id = p_company_id
      and user_id = auth.uid()
      and status = 'active'
  ) then
    raise exception 'Not a member of this company';
  end if;

  loop
    select string_agg(
             substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', (random() * 32)::int + 1, 1),
             ''
           )
      into v_code
      from generate_series(1, 6);
    exit when not exists (select 1 from public.companies where join_code = v_code);
  end loop;

  update public.companies set join_code = v_code where id = p_company_id;
  return v_code;
end;
$$;

create or replace function public.join_device(p_join_code text, p_label text default 'Förare')
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_company public.companies;
  v_seat_count int;
  v_token text;
  v_device public.devices;
begin
  select * into v_company from public.companies where join_code = upper(p_join_code);
  if v_company is null then
    raise exception 'Ogiltig bolagskod';
  end if;

  select count(*) into v_seat_count from public.devices where company_id = v_company.id;
  if v_seat_count >= v_company.seats then
    raise exception 'Inga lediga platser';
  end if;

  v_token := gen_random_uuid()::text;

  insert into public.devices (company_id, token, label, kind)
  values (v_company.id, v_token, coalesce(nullif(p_label, ''), 'Förare'), 'driver')
  returning * into v_device;

  return json_build_object('token', v_device.token, 'id', v_device.id, 'label', v_device.label);
end;
$$;

create or replace function public.device_by_token(p_token text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.devices;
  v_company public.companies;
begin
  select * into v_device from public.devices where token = p_token;
  if v_device is null then
    raise exception 'Enheten hittades inte';
  end if;

  select * into v_company from public.companies where id = v_device.company_id;

  return json_build_object(
    'device', row_to_json(v_device),
    'company', row_to_json(v_company)
  );
end;
$$;

grant execute on function public.regenerate_join_code(uuid) to authenticated;
grant execute on function public.join_device(text, text) to anon, authenticated;
grant execute on function public.device_by_token(text) to anon, authenticated;

-- Auto-create a profile row whenever a new auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data ->> 'name')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===== 20260829000001_smart_signals.sql =====
-- Migration for Smart Signals & H3
--
-- NOTE (2026-09-01): made idempotent so this is a clean no-op against a database created from
-- 20260828999999_baseline_actual_schema.sql, which already includes these columns/tables as
-- verified against production's real shape (alerts.id is uuid, alert_feedback already has
-- device_token). This file is kept for historical record of when these fields were introduced;
-- it is not the source of truth for their shape going forward.

ALTER TABLE public.alerts
ADD COLUMN IF NOT EXISTS h3_index text,
ADD COLUMN IF NOT EXISTS start_time timestamptz,
ADD COLUMN IF NOT EXISTS end_time timestamptz,
ADD COLUMN IF NOT EXISTS demand_score integer,
ADD COLUMN IF NOT EXISTS reasons text[];

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'alerts_demand_score_check'
  ) THEN
    ALTER TABLE public.alerts
      ADD CONSTRAINT alerts_demand_score_check CHECK (demand_score >= 0 AND demand_score <= 100);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.alert_feedback (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id uuid REFERENCES public.alerts(id) ON DELETE CASCADE,
    device_token text,
    result boolean, -- true for 'Fick körning' (thumbs up), false for 'Dött' (thumbs down)
    created_at timestamptz DEFAULT now()
);

-- Index for H3 could be useful
CREATE INDEX IF NOT EXISTS idx_alerts_h3_index ON public.alerts(h3_index);


-- ===== 20260829000002_rpc_worth_it.sql =====
-- RPC for getting smart alerts with "Worth It Score"

CREATE OR REPLACE FUNCTION public.get_smart_alerts(p_lat double precision, p_lon double precision)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result json;
BEGIN
    SELECT json_agg(
        json_build_object(
            'id', a.id,
            'title', a.title,
            'summary', a.summary,
            'lat', a.lat,
            'lon', a.lon,
            'end_time', a.end_time,
            'demand_score', a.demand_score,
            'reasons', a.reasons,
            'distance_km', a.distance_km,
            'worth_it_score', CASE 
                -- Assume speed is ~60 km/h (1 min / km). If minutes left < distance + 10, it's not worth it.
                WHEN EXTRACT(EPOCH FROM (a.end_time - NOW())) / 60 < a.distance_km + 10 THEN 0
                ELSE GREATEST(0, a.demand_score - (a.distance_km * 2))
            END
        )
    ) INTO result
    FROM (
        SELECT 
            id, title, summary, lat, lon, end_time, demand_score, reasons,
            -- Haversine formula for distance in km
            (6371 * acos(cos(radians(p_lat)) * cos(radians(lat)) * 
            cos(radians(lon) - radians(p_lon)) + 
            sin(radians(p_lat)) * sin(radians(lat)))) AS distance_km
        FROM public.alerts
        WHERE end_time > NOW()
    ) a;

    RETURN COALESCE(result, '[]'::json);
END;
$$;

-- ===== 20260901000001_processed_webhook_events.sql =====
-- processed_webhook_events does not exist in production despite being referenced by
-- taxitips-api/worker/src/index.js for Stripe webhook idempotency. Must exist before the
-- worker is deployed, or the first webhook event will crash the handler on insert.

create table if not exists public.processed_webhook_events (
  stripe_event_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now(),
  status text not null,
  error text
);

alter table public.processed_webhook_events enable row level security;
-- Service-role only; no anon/authenticated access needed -- the worker uses the service key.

-- ===== 20260901000002_entitlements.sql =====
-- Entitlement primitive: is this device's company currently allowed to see scored opportunity data?
-- Based on the ACTUAL live schema (verified via psql introspection 2026-08-31), not the git migration
-- files, which have diverged from production (see TAXITIPS_STATUS.md addendum).
--
-- companies.status: 'trial' | 'active' | (others e.g. 'canceled') -- default 'trial'
-- companies.subscription_status: 'inactive' | (presumably 'active'/other stripe-driven values) -- default 'inactive'
-- devices.token: the driver app's bearer identifier (not a FK to auth.users)

create or replace function public.current_entitlement(p_device_token text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select c.status in ('trial', 'active') or c.subscription_status = 'active'
      from public.devices d
      join public.companies c on c.id = d.company_id
      where d.token = p_device_token
      limit 1
    ),
    false
  );
$$;

grant execute on function public.current_entitlement(text) to anon, authenticated;

-- ===== 20260901000003_gate_get_smart_alerts.sql =====
-- Gate get_smart_alerts behind current_entitlement(). Adds p_device_token; ungated/missing
-- token returns an empty result rather than an error, so older clients degrade gracefully
-- until the Flutter app is updated to pass the token (see api_client.dart taxi()).

create or replace function public.get_smart_alerts(p_lat double precision, p_lon double precision, p_device_token text default null)
returns json
language plpgsql
security definer
as $$
declare
    result json;
begin
    if not public.current_entitlement(p_device_token) then
        return '[]'::json;
    end if;

    select json_agg(
        json_build_object(
            'id', a.id,
            'title', a.title,
            'summary', a.summary,
            'lat', a.lat,
            'lon', a.lon,
            'end_time', a.end_time,
            'demand_score', a.demand_score,
            'reasons', a.reasons,
            'distance_km', a.distance_km,
            'worth_it_score', CASE
                WHEN EXTRACT(EPOCH FROM (a.end_time - NOW())) / 60 < a.distance_km + 10 THEN 0
                ELSE GREATEST(0, a.demand_score - (a.distance_km * 2))
            END
        )
    ) INTO result
    FROM (
        SELECT
            id, title, summary, lat, lon, end_time, demand_score, reasons,
            (6371 * acos(cos(radians(p_lat)) * cos(radians(lat)) *
            cos(radians(lon) - radians(p_lon)) +
            sin(radians(p_lat)) * sin(radians(lat)))) AS distance_km
        FROM public.alerts
        WHERE end_time > NOW()
    ) a;

    RETURN COALESCE(result, '[]'::json);
end;
$$;

-- ===== 20260901000004_alert_feedback_rls.sql =====
-- alert_feedback had RLS disabled entirely (relrowsecurity=false) -- anon/authenticated could
-- read, update, or delete any row with no restriction. Feedback data isn't sensitive to read,
-- but write access should be limited to insert-only-by-device, not full CRUD.

alter table public.alert_feedback enable row level security;

create policy alert_feedback_insert_any on public.alert_feedback
  for insert
  with check (true);

create policy alert_feedback_select_none on public.alert_feedback
  for select
  using (false);

-- ===== 20260901000005_drop_legacy_overload_and_public_policy.sql =====
-- Cleanup after 20260901000003_gate_get_smart_alerts.sql: CREATE OR REPLACE with a different
-- argument list created a second overload instead of replacing the function, leaving the old
-- ungated 2-arg get_smart_alerts(double precision, double precision) still callable by anon.
-- Drop it explicitly.
drop function if exists public.get_smart_alerts(double precision, double precision);

-- Contract step: now that get_smart_alerts is gated by current_entitlement() and is
-- SECURITY DEFINER (so it doesn't need direct table grants), the direct public read policy
-- on alerts is no longer needed and is the original security hole this whole fix closes.
drop policy if exists alerts_select_all on public.alerts;

-- ===== 20260901000006_expose_kind_in_get_smart_alerts.sql =====
-- Expose `kind` (e.g. 'traffic' for road-sourced alerts vs the transit-sourced default) in
-- get_smart_alerts so the Flutter client can actually filter road vs. transit disruptions --
-- previously stored on public.alerts but never returned to the client at all.

create or replace function public.get_smart_alerts(p_lat double precision, p_lon double precision, p_device_token text default null)
returns json
language plpgsql
security definer
as $$
declare
    result json;
begin
    if not public.current_entitlement(p_device_token) then
        return '[]'::json;
    end if;

    select json_agg(
        json_build_object(
            'id', a.id,
            'title', a.title,
            'summary', a.summary,
            'kind', a.kind,
            'lat', a.lat,
            'lon', a.lon,
            'end_time', a.end_time,
            'demand_score', a.demand_score,
            'reasons', a.reasons,
            'distance_km', a.distance_km,
            'worth_it_score', CASE
                WHEN EXTRACT(EPOCH FROM (a.end_time - NOW())) / 60 < a.distance_km + 10 THEN 0
                ELSE GREATEST(0, a.demand_score - (a.distance_km * 2))
            END
        )
    ) INTO result
    FROM (
        SELECT
            id, title, summary, kind, lat, lon, end_time, demand_score, reasons,
            (6371 * acos(cos(radians(p_lat)) * cos(radians(lat)) *
            cos(radians(lon) - radians(p_lon)) +
            sin(radians(p_lat)) * sin(radians(lat)))) AS distance_km
        FROM public.alerts
        WHERE end_time > NOW()
    ) a;

    RETURN COALESCE(result, '[]'::json);
end;
$$;

-- ===== 20260902000001_source_events_opportunities.sql =====
-- source_events / opportunities model split (see architecture plan in project notes).
-- Pure "expand" step: introduces both tables, touches nothing existing. public.alerts
-- stays authoritative for reads until a later migration cuts get_smart_alerts over.

-- source_events: latest-known-state per raw fact from an upstream API (upsert on
-- external_id, not append-only -- keeps this simple, avoids an unbounded-growth
-- cleanup job. Explainability is still satisfied because opportunities point at the
-- fact as last observed, which is enough to answer "which source event, which rule").
create table public.source_events (
  id uuid primary key default gen_random_uuid(),
  source text not null,              -- 'trafiklab' | 'trafikverket' | 'smhi' (later)
  external_id text not null unique,  -- e.g. "skane:1234", "tv:mock-e22:0"
  mode text,                         -- 'train' | 'bus' | 'road' | 'weather' | null (unknown)
  fetched_at timestamptz not null default now(),
  active_from timestamptz,
  active_to timestamptz,
  raw jsonb not null,                -- full untouched source payload
  lat double precision,
  lon double precision,
  created_at timestamptz not null default now()
);

create index idx_source_events_external_id on public.source_events (external_id);
create index idx_source_events_active_to on public.source_events (active_to);

alter table public.source_events enable row level security;
-- Service-role only; no anon/authenticated access -- raw source payloads are not
-- meant for direct client consumption (that's what get_opportunity_detail is for).

-- opportunities: one row per derived, scored thing shown to a driver. Superset of
-- today's alerts shape, plus explicit provenance (source_event_ids, rule_id,
-- confidence) that alerts never had.
create table public.opportunities (
  id uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  kind text not null,                -- 'road' | 'transit' (back-compat with existing client filter)
  mode text,                         -- 'train' | 'bus' | 'road' -- new first-class severity axis
  severity_tier text not null default 'unclassified',
  level text not null,               -- 'high'|'medium'|'low'|'ignore'
  title text,
  summary text,
  lat double precision,
  lon double precision,
  h3_index text,
  places jsonb,
  start_time timestamptz,
  end_time timestamptz,
  demand_score integer check (demand_score >= 0 and demand_score <= 100),
  confidence text not null default 'medium', -- 'low'|'medium'|'high' -- explicit, never fabricated
  reasons text[],
  rule_id text,                      -- which function/branch produced this
  source_event_ids uuid[] not null default '{}',
  computed_at timestamptz not null default now(), -- when scoring last ran
  updated_at timestamptz not null default now(),
  expired_reason text
);

create index idx_opportunities_end_time on public.opportunities (end_time);
create index idx_opportunities_h3_index on public.opportunities (h3_index);
create index idx_opportunities_lat_lon on public.opportunities (lat, lon);

alter table public.opportunities enable row level security;
-- No direct table access for anon/authenticated -- reads go through get_smart_alerts /
-- get_opportunity_detail (SECURITY DEFINER, entitlement-gated), same pattern as alerts.

-- ===== 20260902000002_get_smart_alerts_from_opportunities.sql =====
-- Cut get_smart_alerts over to reading from public.opportunities instead of
-- public.alerts. Same signature, same entitlement gate, same Haversine math. No
-- server-side score floor -- everything in range is still returned; anti-overload
-- filtering happens client-side (Phase 4 of the architecture plan), not here.

create or replace function public.get_smart_alerts(p_lat double precision, p_lon double precision, p_device_token text default null)
returns json
language plpgsql
security definer
as $$
declare
    result json;
begin
    if not public.current_entitlement(p_device_token) then
        return '[]'::json;
    end if;

    select json_agg(
        json_build_object(
            'id', a.id,
            'title', a.title,
            'summary', a.summary,
            'kind', a.kind,
            'mode', a.mode,
            'severity_tier', a.severity_tier,
            'confidence', a.confidence,
            'rule_id', a.rule_id,
            'lat', a.lat,
            'lon', a.lon,
            'end_time', a.end_time,
            'demand_score', a.demand_score,
            'reasons', a.reasons,
            'distance_km', a.distance_km,
            'worth_it_score', CASE
                WHEN EXTRACT(EPOCH FROM (a.end_time - NOW())) / 60 < a.distance_km + 10 THEN 0
                ELSE GREATEST(0, a.demand_score - (a.distance_km * 2))
            END
        )
    ) INTO result
    FROM (
        SELECT
            id, title, summary, kind, mode, severity_tier, confidence, rule_id,
            lat, lon, end_time, demand_score, reasons,
            (6371 * acos(cos(radians(p_lat)) * cos(radians(lat)) *
            cos(radians(lon) - radians(p_lon)) +
            sin(radians(p_lat)) * sin(radians(lat)))) AS distance_km
        FROM public.opportunities
        WHERE end_time > NOW()
    ) a;

    RETURN COALESCE(result, '[]'::json);
end;
$$;

