# Generated by Django 6.1.1 on 2026-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=30)),
                ('external_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Länken tillbaka till källan.', max_length=500)),
                ('source_status', models.CharField(blank=True, help_text='Källans statuskod: onsale, offsale, cancelled, postponed, rescheduled.', max_length=30)),
                ('category', models.CharField(db_index=True, help_text='Nyckel i events.timing.CATEGORY_LABELS.', max_length=20)),
                ('segment', models.CharField(blank=True, max_length=60)),
                ('genre', models.CharField(blank=True, max_length=60)),
                ('sub_genre', models.CharField(blank=True, max_length=60)),
                ('start_date', models.DateField(db_index=True, help_text='Lokalt datum. Finns även när tiden inte är satt.')),
                ('start_at', models.DateTimeField(blank=True, help_text='NULL = starttiden inte satt (TBA).', null=True)),
                ('time_known', models.BooleanField(default=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_basis', models.CharField(help_text='source, estimated eller unknown.', max_length=10)),
                ('end_note', models.CharField(blank=True, help_text='Hur sluttiden togs fram, i klartext.', max_length=200)),
                ('multi_day', models.BooleanField(default=False)),
                ('venue_id', models.CharField(blank=True, max_length=60)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, db_index=True, help_text='Marknad (sl, vt, skane ...) från koordinaten. NULL, aldrig tom sträng, när den är okänd.', max_length=30, null=True)),
                ('hidden_reason', models.CharField(blank=True, help_text='Tomt = visas för föraren. Annars varför inte.', max_length=200)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Källans svar, nedbantat till det som förklarar raden.')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('missing_since', models.DateTimeField(blank=True, help_text='Källan slutade lista evenemanget. Döljs direkt, raderas efter 24 timmar.', null=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_date', 'start_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='events_source_external_id')],
            },
        ),
    ]
