# Generated by Django 6.1.1 on 2026-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, help_text='PredictHQ phq_attendance: förutsagt antal besökare.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='local_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
