/**
 * Exempeldata för demosidan. Inget här är live.
 *
 * Reglerna från appen gäller även här:
 *  - Flyg och färja: inga påhittade passagerarantal. Bara "när" och "varför".
 *  - Evenemang får säga ungefär hur många som är där.
 *  - Inga namn på datakällor i texten.
 *  - Enkel svenska: korta meningar, vanliga ord.
 *
 * Tider räknas från när sidan öppnas, så "18:42" och "om 12 min" alltid
 * stämmer med varandra. `t(n)` ger klockslaget om n minuter. `ongoing`
 * betyder att det redan pågår; då är `minutes` hur länge sedan det började.
 */

export const CATEGORIES = [
  { id: "alla", label: "Alla" },
  { id: "tag", label: "Tåg" },
  { id: "buss", label: "Buss" },
  { id: "flyg", label: "Flyg" },
  { id: "farja", label: "Färja" },
  { id: "event", label: "Evenemang" },
  { id: "vag", label: "Väg" },
];

export const STRENGTHS = {
  stark: { label: "Stark", note: "Ger notis. Många behöver taxi." },
  medel: { label: "Medel", note: "Ger notis. Värt att titta på." },
  svag: { label: "Svag", note: "Syns i listan. Ingen notis." },
};

export const TIPS = [
  {
    id: "stockholm-c",
    cat: "tag",
    kind: "Avgång inställd",
    strength: "stark",
    place: "Stockholm C",
    city: "Stockholm",
    lngLat: [18.0582, 59.3301],
    minutes: 12,
    bearing: -28,
    what: (t) => `Avgången ${t(12)} mot Västerås är inställd.`,
    next: (t) => `Nästa avgång ${t(72)} (om 1 tim) · Ingen buss ersätter`,
    why: "Tåget är inställt och nästa går om en timme. Många behöver åka vidare på annat sätt.",
    signals: ["Avgången är inställd", "Nästa tåg går om 1 timme", "Ingen ersättningsbuss"],
    tour: "Tåget är inställt. Folk står kvar på stationen. Du ser det först.",
  },
  {
    id: "odenplan",
    cat: "buss",
    kind: "Tunnelbana · Står still",
    strength: "stark",
    place: "Odenplan",
    city: "Stockholm",
    lngLat: [18.0479, 59.343],
    minutes: -6,
    ongoing: true,
    bearing: 35,
    what: () => "Gröna linjen står still vid Odenplan. Det gäller båda hållen.",
    next: () => "Beräknas gå igen om cirka 40 min",
    why: "Tunnelbanan står still mitt i kvällstrafiken. Folk väntar vid uppgångarna.",
    signals: ["Stopp i tunnelbanan", "Båda riktningarna", "Kvällstrafik"],
    tour: "Tunnelbanan står still. Många behöver ett annat sätt att åka. Appen visar var de väntar.",
  },
  {
    id: "arlanda",
    cat: "flyg",
    kind: "Flyg · Sista planet",
    strength: "stark",
    place: "Arlanda Terminal 5",
    city: "Sigtuna",
    lngLat: [17.9362, 59.6512],
    minutes: 26,
    bearing: -60,
    what: (t) => `Kvällens sista plan från London landar ${t(26)}.`,
    next: () => "Sedan landar inga fler plan på minst 2 timmar",
    why: "Det är kvällens sista plan till terminalen. Efter det kommer inga fler på länge.",
    signals: ["Sista landningen i kväll", "Inga fler plan på 2 timmar"],
    tour: "Kvällens sista plan landar. Sedan kommer inga fler. Du vet när det är värt att vänta.",
  },
  {
    id: "uppsala-c",
    cat: "tag",
    kind: "Tåg · Försenat",
    strength: "medel",
    place: "Uppsala C",
    city: "Uppsala",
    lngLat: [17.6466, 59.8582],
    minutes: 18,
    bearing: 20,
    what: (t) => `Tåget från Stockholm är 35 min sent. Det kommer in ${t(18)}.`,
    next: (t) => `Sista bussen mot Gränby gick ${t(-4)}`,
    why: "Tåget kommer in sent. Flera bussar har slutat gå för kvällen.",
    signals: ["Försenat tåg", "Sista bussen har gått"],
    tour: "Tåget är sent och bussarna har slutat gå. Då behövs taxi.",
  },
  {
    id: "ullevi",
    cat: "event",
    kind: "Evenemang · Match slutar",
    strength: "stark",
    place: "Ullevi",
    city: "Göteborg",
    lngLat: [11.9873, 57.7059],
    minutes: 35,
    bearing: -15,
    what: (t) => `Matchen på Ullevi slutar cirka ${t(35)}. Ungefär 30 000 personer är där.`,
    next: () => "Spårvagnarna vid Ullevi blir fulla direkt",
    why: "Ett stort evenemang slutar. Många går ut samtidigt och vill hem.",
    signals: ["Stort evenemang", "Slutar om ungefär en halvtimme"],
    tour: "Matchen slutar snart. Appen säger till innan folket kommer ut.",
  },
  {
    id: "visby",
    cat: "farja",
    kind: "Färja · På väg in",
    strength: "stark",
    place: "Visby hamn",
    city: "Visby",
    lngLat: [18.2835, 57.6365],
    minutes: 22,
    bearing: 70,
    what: (t) => `Färjan från Nynäshamn lägger till i Visby ${t(22)}.`,
    next: () => "Nästa färja kommer i morgon bitti",
    why: "Kvällens sista färja lägger till. Få bussar går så här sent.",
    signals: ["Färja på väg in", "Sista för kvällen", "Få bussar sent"],
    tour: "Färjan lägger till. Du ser exakt när och kan vara på plats i tid.",
  },
  {
    id: "e4-sundsvall",
    cat: "vag",
    kind: "Väg · Olycka",
    strength: "medel",
    place: "E4 vid Sundsvallsbron",
    city: "Sundsvall",
    lngLat: [17.3407, 62.3891],
    minutes: -14,
    ongoing: true,
    bearing: 10,
    what: () => "Olycka på E4 vid Sundsvallsbron. Trafiken står still norrut.",
    next: () => "Bussarna på E4 står också i kön",
    why: "Vägen är stoppad. Folk som ska vidare kan behöva en annan väg och en taxi.",
    signals: ["Olycka på E4", "Stopp i en riktning", "Bussar påverkas"],
    tour: "En olycka stoppar trafiken. Du får veta var folk behöver åka vidare.",
  },
  {
    id: "lulea",
    cat: "flyg",
    kind: "Flyg · Sent plan",
    strength: "medel",
    place: "Luleå Airport",
    city: "Luleå",
    lngLat: [22.1167, 65.5478],
    minutes: 41,
    bearing: -40,
    what: (t) => `Planet från Stockholm landar ${t(41)}. Det är 50 min sent.`,
    next: () => "Sista flygbussen in till stan har redan gått",
    why: "Planet landar sent. Bussen in till stan har slutat gå.",
    signals: ["Försenat plan", "Sista bussen har gått"],
  },
  {
    id: "umea",
    cat: "buss",
    kind: "Buss · Linje inställd",
    strength: "svag",
    place: "Vasaplan",
    city: "Umeå",
    lngLat: [20.2651, 63.8265],
    minutes: 15,
    bearing: 25,
    what: (t) => `Bussen ${t(15)} mot Ålidhem är inställd.`,
    next: (t) => `Nästa buss ${t(35)} (om 20 min)`,
    why: "En buss är inställd, men nästa kommer snart. Därför bara Svag.",
    signals: ["En avgång inställd", "Nästa går om 20 min"],
  },
  {
    id: "orebro",
    cat: "tag",
    kind: "Tåg · Försenat",
    strength: "medel",
    place: "Örebro C",
    city: "Örebro",
    lngLat: [15.2107, 59.278],
    minutes: 28,
    bearing: -20,
    what: (t) => `Tåget från Göteborg är 45 min sent. Det kommer in ${t(28)}.`,
    next: () => "Inga bussar till Adolfsberg efter klockan 23",
    why: "Tåget kommer sent på kvällen. Det är svårt att åka vidare med buss.",
    signals: ["Försenat tåg", "Sent på kvällen"],
  },
  {
    id: "linkoping",
    cat: "event",
    kind: "Evenemang · Hockey slutar",
    strength: "medel",
    place: "Saab Arena",
    city: "Linköping",
    lngLat: [15.6356, 58.4174],
    minutes: 48,
    bearing: 40,
    what: (t) => `Hockeymatchen slutar cirka ${t(48)}. Ungefär 7 000 personer är där.`,
    next: () => "Extrabussar går, men inte till alla delar av stan",
    why: "Ett evenemang slutar sent. Många ska åt olika håll samtidigt.",
    signals: ["Evenemang slutar", "Kvällstid"],
  },
  {
    id: "karlstad",
    cat: "tag",
    kind: "Tåg · Lite sent",
    strength: "svag",
    place: "Karlstad C",
    city: "Karlstad",
    lngLat: [13.4991, 59.378],
    minutes: 9,
    bearing: 15,
    what: (t) => `Tåget från Oslo är 10 min sent. Det kommer in ${t(9)}.`,
    next: () => "Bussarna går som vanligt",
    why: "Tåget är bara lite sent och bussarna går. Därför bara Svag.",
    signals: ["Liten försening", "Bussar går"],
  },
  {
    id: "helsingborg",
    cat: "farja",
    kind: "Färja · På väg in",
    strength: "svag",
    place: "Helsingborg färjeläge",
    city: "Helsingborg",
    lngLat: [12.6941, 56.0436],
    minutes: 7,
    bearing: -50,
    what: (t) => `Färjan från Helsingør lägger till ${t(7)}.`,
    next: () => "Nästa färja om 20 min",
    why: "Färjorna går ofta här. Det är sällan en stor topp. Därför bara Svag.",
    signals: ["Färja på väg in", "Går ofta"],
  },
];

/** Turen för säljmöten: sex tips, i en ordning som berättar en historia. */
export const TOUR = ["stockholm-c", "odenplan", "arlanda", "ullevi", "visby", "e4-sundsvall"];

export const TOUR_END =
  "Varje tips säger var, när och varför. Du bestämmer alltid själv om du kör dit.";
