/**
 * Egen mörk kartstil i midnatt, byggd på OpenFreeMaps fria vektorplattor
 * (OpenMapTiles-schemat, ingen API-nyckel). Vi ritar bara det föraren
 * behöver: land, vatten, vägar, järnväg, hus i 3D och ortnamn. Guld är
 * reserverat för tipsen, så kartan själv har inget guld.
 */

const C = {
  land: "#1b2946",
  landDeep: "#14213d",
  water: "#0a1324",
  waterLine: "#0f1b33",
  wood: "#1a2a45",
  park: "#1b2d47",
  residential: "#1d2b48",
  aeroway: "#22324f",
  minor: "#26365a",
  major: "#33456b",
  motorway: "#4b5d84",
  rail: "#3b4c70",
  building: "#2a3a5c",
  border: "rgba(245,247,250,0.28)",
  label: "#d5dbe6",
  labelSoft: "#93a0b8",
  halo: "#0d1729",
};

const NAME = ["coalesce", ["get", "name:sv"], ["get", "name"]];

export function navyStyle() {
  return {
    version: 8,
    name: "Taxi Tips midnatt",
    projection: { type: "globe" },
    sky: {
      "sky-color": "#0d1729",
      "horizon-color": "#253551",
      "fog-color": "#14213d",
      "sky-horizon-blend": 0.6,
      "horizon-fog-blend": 0.6,
      "fog-ground-blend": 0.85,
      "atmosphere-blend": ["interpolate", ["linear"], ["zoom"], 0, 0.9, 6, 0.4, 10, 0],
    },
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
    sources: {
      omt: { type: "vector", url: "https://tiles.openfreemap.org/planet" },
    },
    layers: [
      { id: "bg", type: "background", paint: { "background-color": C.land } },
      {
        id: "wood",
        type: "fill",
        source: "omt",
        "source-layer": "landcover",
        filter: ["==", ["get", "class"], "wood"],
        paint: { "fill-color": C.wood, "fill-opacity": 0.7 },
      },
      {
        id: "residential",
        type: "fill",
        source: "omt",
        "source-layer": "landuse",
        filter: ["match", ["get", "class"], ["residential", "suburb", "neighbourhood"], true, false],
        paint: { "fill-color": C.residential, "fill-opacity": 0.8 },
      },
      {
        id: "park",
        type: "fill",
        source: "omt",
        "source-layer": "park",
        paint: { "fill-color": C.park, "fill-opacity": 0.7 },
      },
      {
        id: "water",
        type: "fill",
        source: "omt",
        "source-layer": "water",
        filter: ["!=", ["get", "brunnel"], "tunnel"],
        paint: { "fill-color": C.water },
      },
      {
        id: "waterway",
        type: "line",
        source: "omt",
        "source-layer": "waterway",
        paint: {
          "line-color": C.waterLine,
          "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.5, 14, 2.5],
        },
      },
      {
        id: "aeroway",
        type: "fill",
        source: "omt",
        "source-layer": "aeroway",
        filter: ["match", ["geometry-type"], ["Polygon", "MultiPolygon"], true, false],
        paint: { "fill-color": C.aeroway, "fill-opacity": 0.8 },
      },
      {
        id: "runway",
        type: "line",
        source: "omt",
        "source-layer": "aeroway",
        filter: ["match", ["get", "class"], ["runway", "taxiway"], true, false],
        paint: {
          "line-color": C.major,
          "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 11, 2, 17, 40],
        },
      },
      {
        id: "road-minor",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 12,
        filter: ["match", ["get", "class"], ["minor", "service", "track"], true, false],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": C.minor,
          "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 12, 0.5, 16, 5, 20, 18],
        },
      },
      {
        id: "road-major",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 7,
        filter: ["match", ["get", "class"], ["primary", "secondary", "tertiary", "trunk"], true, false],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": C.major,
          "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 7, 0.4, 12, 1.6, 16, 8, 20, 24],
        },
      },
      {
        id: "rail",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 8,
        filter: ["match", ["get", "class"], ["rail", "transit"], true, false],
        paint: {
          "line-color": C.rail,
          "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.6, 16, 2.4],
          "line-dasharray": [3, 2],
        },
      },
      {
        id: "road-motorway",
        type: "line",
        source: "omt",
        "source-layer": "transportation",
        minzoom: 5,
        filter: ["==", ["get", "class"], "motorway"],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": C.motorway,
          "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 5, 0.5, 10, 1.6, 16, 10, 20, 30],
        },
      },
      {
        id: "border",
        type: "line",
        source: "omt",
        "source-layer": "boundary",
        filter: ["all", ["==", ["get", "admin_level"], 2], ["!=", ["get", "maritime"], 1]],
        paint: {
          "line-color": C.border,
          "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.8, 10, 2],
          "line-dasharray": [2, 2],
        },
      },
      {
        id: "building-3d",
        type: "fill-extrusion",
        source: "omt",
        "source-layer": "building",
        minzoom: 13.5,
        paint: {
          "fill-extrusion-color": C.building,
          "fill-extrusion-height": ["coalesce", ["get", "render_height"], 8],
          "fill-extrusion-base": ["coalesce", ["get", "render_min_height"], 0],
          "fill-extrusion-opacity": ["interpolate", ["linear"], ["zoom"], 13.5, 0, 14.5, 0.92],
          "fill-extrusion-vertical-gradient": true,
        },
      },
      {
        id: "road-label",
        type: "symbol",
        source: "omt",
        "source-layer": "transportation_name",
        minzoom: 14,
        filter: ["match", ["get", "class"], ["primary", "secondary", "tertiary", "minor", "trunk"], true, false],
        layout: {
          "symbol-placement": "line",
          "text-field": NAME,
          "text-font": ["Noto Sans Regular"],
          "text-size": 11,
        },
        paint: { "text-color": C.labelSoft, "text-halo-color": C.halo, "text-halo-width": 1.2 },
      },
      {
        id: "water-label",
        type: "symbol",
        source: "omt",
        "source-layer": "water_name",
        filter: ["match", ["geometry-type"], ["Point", "MultiPoint"], true, false],
        layout: {
          "text-field": NAME,
          "text-font": ["Noto Sans Italic"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 3, 10, 8, 13],
          "text-letter-spacing": 0.15,
        },
        paint: { "text-color": "#4f6286", "text-halo-color": C.water, "text-halo-width": 1 },
      },
      {
        id: "place-town",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        minzoom: 7,
        filter: ["match", ["get", "class"], ["town", "suburb", "village"], true, false],
        layout: {
          "text-field": NAME,
          "text-font": ["Noto Sans Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 7, 11, 14, 14],
          "text-max-width": 8,
        },
        paint: { "text-color": C.labelSoft, "text-halo-color": C.halo, "text-halo-width": 1.2 },
      },
      {
        id: "place-city",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        minzoom: 3,
        filter: ["==", ["get", "class"], "city"],
        layout: {
          "text-field": NAME,
          "text-font": ["Noto Sans Bold"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 4, 11, 8, 14, 12, 18],
          "text-max-width": 8,
        },
        paint: { "text-color": C.label, "text-halo-color": C.halo, "text-halo-width": 1.4 },
      },
      {
        id: "place-country",
        type: "symbol",
        source: "omt",
        "source-layer": "place",
        maxzoom: 6,
        filter: ["==", ["get", "class"], "country"],
        layout: {
          "text-field": NAME,
          "text-font": ["Noto Sans Bold"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 2, 10, 5, 14],
          "text-transform": "uppercase",
          "text-letter-spacing": 0.2,
        },
        paint: { "text-color": "rgba(245,247,250,0.45)", "text-halo-color": C.halo, "text-halo-width": 1 },
      },
    ],
  };
}
