# Generated by Django 6.1.1 on 2026-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FerryArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.BigIntegerField(unique=True)),
                ('ship_name', models.CharField(blank=True, max_length=100)),
                ('ship_type', models.PositiveSmallIntegerField(blank=True, help_text='AIS ShipType. NULL tills fartygets ShipStaticData hörts.', null=True)),
                ('length_m', models.PositiveSmallIntegerField(blank=True, help_text='Dimension A+B. Det enda i AIS som säger något om hur stor färjan är.', null=True)),
                ('destination', models.CharField(blank=True, help_text='Fritext från besättningen.', max_length=40)),
                ('port_name', models.CharField(blank=True, db_index=True, help_text='Hamnrutan fartyget senast sågs i (maritime/ports.py). Tom = utanför alla.', max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed_knots', models.FloatField(blank=True, help_text="SOG. NULL = fartygets AIS säger 'saknas'.", null=True)),
                ('nav_status', models.PositiveSmallIntegerField(blank=True, help_text='5 = förtöjd, 1 = ankrad.', null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='AIS-ETA mot fartygets nästa destination. NULL när den saknas eller är inaktuell.', null=True)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Senaste positionens AIS-tid.', null=True)),
                ('was_underway', models.BooleanField(default=False, help_text='Setts i fart under det här anlöpet. Krävs för att inbromsning ska räknas som ankomst.')),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Ankomsten är redan hanterad. Släpps när färjan avgår eller varit tyst i tre timmar.')),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ferry_arrivals',
                'ordering': ['-timestamp'],
            },
        ),
    ]
