# Generated by Django 6.1.1 on 2026-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AisVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('call_sign', models.CharField(blank=True, max_length=10)),
                ('imo', models.PositiveIntegerField(blank=True, null=True)),
                ('ship_type', models.PositiveSmallIntegerField(blank=True, help_text='AIS ShipType. NULL tills statisk data hörts.', null=True)),
                ('ais_class', models.CharField(blank=True, help_text='A eller B, efter vilken meddelandetyp fartyget sänder.', max_length=1)),
                ('length_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('width_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draught_m', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=40)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed_knots', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, help_text='COG i grader. NULL = saknas (360).', null=True)),
                ('heading', models.PositiveSmallIntegerField(blank=True, help_text='TrueHeading. NULL = saknas (511).', null=True)),
                ('nav_status', models.PositiveSmallIntegerField(blank=True, help_text='Bara klass A och långdistans-AIS sänder den.', null=True)),
                ('port_name', models.CharField(blank=True, db_index=True, max_length=60)),
                ('last_message_type', models.CharField(blank=True, max_length=40)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('position_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('static_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ais_vessels',
                'ordering': ['-position_at'],
            },
        ),
    ]
