# Generated by Django 6.1.1 on 2026-09-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0002_aisvessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerryCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=80, unique=True)),
                ('mmsi', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, max_length=100)),
                ('terminal', models.CharField(help_text='Nyckel i maritime.register.TERMINALS.', max_length=30)),
                ('started_at', models.DateTimeField(help_text='Första positionen i bufferten när fartyget sågs närma sig.')),
                ('berth_eta', models.DateTimeField(blank=True, help_text='Senaste uppskattade kajtid.', null=True)),
                ('eta_basis', models.CharField(blank=True, help_text='distance eller ais_eta -- aldrig en blandning.', max_length=10)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('first_estimate_at', models.DateTimeField(blank=True, null=True)),
                ('first_berth_eta', models.DateTimeField(blank=True, null=True)),
                ('estimates', models.JSONField(blank=True, default=list, help_text='Uppskattningar som ändrats minst två minuter.')),
                ('arrived_at', models.DateTimeField(blank=True, help_text='Vid kaj enligt AIS: i terminalrutan under 1 knop.', null=True)),
                ('tip_external_id', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ferry_calls',
                'ordering': ['-started_at'],
            },
        ),
    ]
