# Generated by Django 6.1.1 on 2026-09-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0003_ferry_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerryTimetableCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True)),
                ('trip_id', models.CharField(max_length=40)),
                ('agency', models.CharField(max_length=100)),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('stop_id', models.CharField(max_length=40)),
                ('stop_name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sequence', models.PositiveIntegerField()),
                ('arrival_at', models.DateTimeField(blank=True, db_index=True, help_text='Tom på turens första anlöp.', null=True)),
                ('departure_at', models.DateTimeField(blank=True, db_index=True, help_text='Tom på turens sista anlöp.', null=True)),
                ('origin_name', models.CharField(max_length=120)),
                ('destination_name', models.CharField(max_length=120)),
                ('imported_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ferry_timetable_calls',
                'indexes': [models.Index(fields=['stop_id', 'arrival_at'], name='ferry_tt_stop_arrival_idx')],
            },
        ),
    ]
