# Generated by Django 6.1.1 on 2026-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0004_ferry_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferrytimetablecall',
            name='stop_has_road',
            field=models.BooleanField(default=True, help_text='Buss, spårvagn eller tåg inom 400 m enligt samma GTFS-fil. Nej = troligen en ö utan bilväg.'),
        ),
    ]
