# Generated by Django 6.1.1 on 2026-09-05 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('signature', models.CharField(help_text="LocationSignature, t.ex. 'Cst'.", max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rail_station',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StopArea',
            fields=[
                ('gid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('sl', 'SL'), ('vt', 'Västtrafik')], db_index=True, max_length=4)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stop_area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.TextField(unique=True)),
                ('kind', models.CharField(help_text='transit eller road', max_length=20)),
                ('mode', models.CharField(blank=True, choices=[('train', 'Tåg'), ('metro', 'Tunnelbana'), ('tram', 'Spårvagn'), ('bus', 'Buss'), ('road', 'Väg'), ('boat', 'Båt'), ('unknown', 'Okänt')], db_index=True, max_length=20)),
                ('severity_tier', models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], db_index=True, default='disruption_unclassified', max_length=40)),
                ('level', models.CharField(default='medium', max_length=20)),
                ('title', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('h3_index', models.CharField(blank=True, db_index=True, max_length=20)),
                ('places', models.JSONField(blank=True, default=list)),
                ('region', models.CharField(blank=True, db_index=True, help_text='Marknad: skane, sl, vt, rail... Bär geofencet för tips UTAN koordinat -- utan det nådde ett Stockholmstips en Malmöförare.', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('demand_score', models.IntegerField(default=0)),
                ('confidence', models.CharField(choices=[('high', 'Hög — tydligt i källdatan'), ('medium', 'Medel'), ('low', 'Låg — osäker tolkning')], default='medium', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Motiveringarna bakom poängen.')),
                ('rule_id', models.CharField(blank=True, help_text='mode.tier, för spårbarhet.', max_length=80)),
                ('source_event_ids', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_reason', models.CharField(blank=True, max_length=60)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Skrivs ENDAST av push-steget. Se klassdocstringen.', null=True)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'db_table': 'opportunities',
                'ordering': ['-demand_score'],
                'indexes': [models.Index(fields=['end_time', 'severity_tier'], name='opportuniti_end_tim_ceadb0_idx'), models.Index(fields=['lat', 'lon'], name='opportuniti_lat_375daf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('demand_score__gte', 0), ('demand_score__lte', 100)), name='demand_score_0_100')],
            },
        ),
        migrations.CreateModel(
            name='RailAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Normaliserad form: tier|mode|station|har_alternativ|timme. INTE titeln -- 28 av 28 tågtitlar är unika, cache på titel ger 0% träff.', max_length=200)),
                ('rule_score', models.IntegerField(help_text='Vad regelverket gav.')),
                ('model_score', models.IntegerField(help_text='Vad modellen föreslog.')),
                ('final_score', models.IntegerField(help_text='min(rule, model) -- aldrig högre.')),
                ('verdict', models.TextField(blank=True, help_text='Modellens motivering.')),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.opportunity')),
            ],
            options={
                'db_table': 'rail_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], max_length=40)),
                ('mode', models.CharField(blank=True, choices=[('train', 'Tåg'), ('metro', 'Tunnelbana'), ('tram', 'Spårvagn'), ('bus', 'Buss'), ('road', 'Väg'), ('boat', 'Båt'), ('unknown', 'Okänt')], help_text='Tomt = gäller alla färdsätt.', max_length=20)),
                ('condition', models.CharField(blank=True, help_text="Vilken gren i klassificeringen, t.ex. 'stated_alternative'.", max_length=80)),
                ('floor', models.IntegerField(blank=True, help_text='Poängen blir minst detta.', null=True)),
                ('cap', models.IntegerField(blank=True, help_text='Poängen blir högst detta.', null=True)),
                ('confidence', models.CharField(choices=[('high', 'Hög — tydligt i källdatan'), ('medium', 'Medel'), ('low', 'Låg — osäker tolkning')], default='medium', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Varför regeln ser ut så här.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scoring_rule',
                'ordering': ['tier', 'mode'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'mode', 'condition'), name='uniq_scoring_rule')],
            },
        ),
        migrations.CreateModel(
            name='SourceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, help_text='trafikverket_rail, trafiklab, sl, vt, trafikverket, smhi', max_length=40)),
                ('external_id', models.TextField(unique=True)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(help_text='Payloaden precis som den kom.')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_events',
                'indexes': [models.Index(fields=['source', 'active_to'], name='source_even_source_23153f_idx')],
            },
        ),
    ]
