# Generated by Django 6.1.1 on 2026-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='expired_reason',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
