# Generated by Django 6.1.1 on 2026-09-05 22:38

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_opportunity_expired_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='computed_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='sourceevent',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='sourceevent',
            name='fetched_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
