# Generated by Django 6.1.1 on 2026-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_opportunity_computed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Samma nyckel som core.geo.REGION_ANCHOR: skane, sl, vt, ul, ...', max_length=30, unique=True)),
                ('threshold_minutes', models.IntegerField(default=20, help_text='Minuter försening som ger rätt till ersättning.')),
                ('taxi_cap_kr', models.IntegerField(help_text='Högsta ersättning för taxi/alternativ transport, i kronor.')),
                ('excluded_modes', models.JSONField(blank=True, default=list, help_text='Färdsätt där taxi INTE ersätts (t.ex. X-trafik: ["train"]).')),
                ('filing_deadline_days', models.IntegerField(default=60, help_text='Frist för att ansöka, i dagar.')),
                ('source_url', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, help_text='Flaggar osäkra/obekräftade siffror -- se docs/.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'region_compensation_rule',
                'ordering': ['region'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='compensation_amount_kr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='compensation_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
