# Generated by Django 6.1.1 on 2026-09-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_regioncompensationrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='region',
            field=models.CharField(blank=True, db_index=True, help_text="Marknad: skane, sl, vt, rail... Bär geofencet för tips UTAN koordinat -- utan det nådde ett Stockholmstips en Malmöförare. NULL, aldrig tom sträng, när marknaden är okänd: get_smart_alerts gör coalesce(region,'skane') för platslösa tips, och '' hade matchat ingen marknad alls -- tipset hade försvunnit tyst.", max_length=30, null=True),
        ),
    ]
