# Generated by Django 6.1.1 on 2026-09-08 06:22

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_opportunity_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.TextField(db_index=True)),
                ('verdict', models.CharField(choices=[('heading', 'Kör dit'), ('fare', 'Fick körning'), ('empty', 'Ingen kund')], max_length=10)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.opportunity')),
            ],
            options={
                'db_table': 'opportunity_feedback',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'device_token', 'verdict'), name='uniq_feedback_per_device_verdict')],
            },
        ),
    ]
