# Generated by Django 6.1.1 on 2026-09-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opportunityfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_last_departure',
            field=models.BooleanField(default=False, help_text='Sista avgången härifrån idag -- ingen kommer efter.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_departure_minutes',
            field=models.IntegerField(blank=True, db_index=True, help_text='Minuter till nästa avgång härifrån. NULL = okänt.', null=True),
        ),
    ]
