# Generated by Django 6.1.1 on 2026-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_opportunity_is_last_departure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStatus',
            fields=[
                ('source', models.CharField(help_text='trafikverket_rail, trafiklab, sl, vt, trafikverket, smhi', max_length=40, primary_key=True, serialize=False)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('events', models.IntegerField(default=0, help_text='Antal larm källan gav.')),
                ('written', models.IntegerField(default=0, help_text='Antal tips som skrevs.')),
                ('duration_ms', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'source statuses',
                'db_table': 'source_status',
                'ordering': ['source'],
            },
        ),
    ]
