# Generated by Django 6.1.1 on 2026-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sourcestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcestatus',
            name='detail',
            field=models.JSONField(blank=True, default=dict, help_text='Utfall per delkälla, när källan har flera. Trafiklab pollar femton regionala operatörer och en av dem kan 404:a utan att hämtningen som helhet misslyckas -- utan det här fältet syns bara summan, och en region som tyst försvunnit ser ut som en region utan störningar.'),
        ),
    ]
