# Generated by Django 6.1.1 on 2026-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sourcestatus_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='alternative_note',
            field=models.TextField(blank=True, help_text='Vad källan säger om alternativet, i källans egna ord. Tomt när inget angetts -- vi hittar aldrig på ett alternativ: en förare som kör till en perrong där ersättningsbussen redan står gör en bomresa.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='has_alternative',
            field=models.BooleanField(default=False, help_text='Källan anger ersättningstrafik eller annan väg vidare.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_departure_at',
            field=models.DateTimeField(blank=True, help_text='Absolut tidpunkt för nästa avgång. Den som visas för föraren: minuterna ovan mättes vid pollningen och åldras med tipset, klockslaget gör inte det.', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='next_departure_minutes',
            field=models.IntegerField(blank=True, db_index=True, help_text='Minuter till nästa avgång, mätt när tipset skrevs. NULL = okänt.', null=True),
        ),
    ]
