# Generated by Django 6.1.1 on 2026-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_opportunity_alternative_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioncompensationrule',
            name='cap_per_person',
            field=models.BooleanField(blank=True, help_text='Gäller taket per resenär (True) eller per resa/bil (False)? NULL = källan säger inget, och då påstår vi inget heller. Skillnaden är stor för en förare: Skånetrafikens 2 960 kr gäller PER betalande resenär, medan SL uttryckligen skriver att beloppet inte blir högre om man samåker -- fyra strandsatta resenärer är två helt olika affärer i de två fallen.', null=True),
        ),
    ]
