# Generated by Django 6.1.1 on 2026-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_regioncompensationrule_cap_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='compensation_per_person',
            field=models.BooleanField(blank=True, help_text='Gäller taket per resenär? NULL = huvudmannen skriver inte ut det.', null=True),
        ),
    ]
