# Generated by Django 6.1.1 on 2026-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_opportunity_compensation_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoparea',
            name='site_id',
            field=models.CharField(blank=True, db_index=True, help_text="SL:s site-id, ett ANNAT id-rum än gid (som är stop_area-id). Behövs för /v1/sites/{site_id}/departures, som är enda vägen till 'när går nästa buss' i Stockholm. Tomt för Västtrafik.", max_length=20),
        ),
    ]
