# Generated by Django 6.1.1 on 2026-09-08 23:09

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stoparea_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_key', models.TextField(db_index=True, help_text="Förarens device-token, eller 'user:<uuid>' för inloggad ägare.")),
                ('opportunity_external_id', models.TextField(db_index=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, help_text='Förarens egen anteckning.')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='core.opportunity')),
            ],
            options={
                'db_table': 'opportunity_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_key', '-created_at'], name='opportunity_owner_k_2d12bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'opportunity_external_id'), name='uniq_favorite_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_external_id', models.TextField(db_index=True)),
                ('device_id', models.UUIDField(db_index=True)),
                ('device_token', models.TextField(blank=True, db_index=True)),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Tipset som det såg ut när notisen gick.')),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('opportunity', models.ForeignKey(blank=True, help_text='NULL efter att tipset gallrats -- snapshot bär innehållet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.opportunity')),
            ],
            options={
                'verbose_name_plural': 'push deliveries',
                'db_table': 'push_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_token', '-created_at'], name='push_delive_device__21a14c_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'opportunity_external_id'), name='uniq_push_per_device_opportunity')],
            },
        ),
    ]
