# Generated by Django 6.1.1 on 2026-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_opportunityfavorite_pushdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='mode',
            field=models.CharField(blank=True, choices=[('train', 'Tåg'), ('metro', 'Tunnelbana'), ('tram', 'Spårvagn'), ('bus', 'Buss'), ('road', 'Väg'), ('boat', 'Båt'), ('flight', 'Flyg'), ('unknown', 'Okänt')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='severity_tier',
            field=models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('arrival_wave', 'Ankomstvåg'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], db_index=True, default='disruption_unclassified', max_length=40),
        ),
        migrations.AlterField(
            model_name='railassessment',
            name='final_score',
            field=models.IntegerField(help_text='Omklassning: model_score. Dämpning: min(rule, model).'),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='mode',
            field=models.CharField(blank=True, choices=[('train', 'Tåg'), ('metro', 'Tunnelbana'), ('tram', 'Spårvagn'), ('bus', 'Buss'), ('road', 'Väg'), ('boat', 'Båt'), ('flight', 'Flyg'), ('unknown', 'Okänt')], help_text='Tomt = gäller alla färdsätt.', max_length=20),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='tier',
            field=models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('arrival_wave', 'Ankomstvåg'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], max_length=40),
        ),
    ]
