# Generated by Django 6.1.1 on 2026-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_opportunity_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='severity_tier',
            field=models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('arrival_wave', 'Ankomstvåg'), ('last_arrival', 'Sista ankomsten'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], db_index=True, default='disruption_unclassified', max_length=40),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='tier',
            field=models.CharField(choices=[('line_paused', 'Hela linjen stoppad'), ('vehicle_cancelled', 'Enstaka avgång inställd'), ('line_delayed', 'Försening på linjen'), ('vehicle_delayed', 'Enstaka avgång försenad'), ('arrival_wave', 'Ankomstvåg'), ('last_arrival', 'Sista ankomsten'), ('road_accident_or_closure', 'Olycka/avstängning'), ('road_work_or_queue', 'Vägarbete/kö'), ('road_work', 'Vägarbete'), ('disruption_unclassified', 'Osäker bedömning'), ('ignore', 'Ignoreras')], max_length=40),
        ),
    ]
