# Generated by Django 6.1.1 on 2026-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pushdelivery_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='ai_adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
