# Generated by Django 6.1.1 on 2026-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_opportunity_ai_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='municipality_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
    ]
