# Generated by Django 6.1.1 on 2026-09-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_opportunity_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=40)),
                ('effect', models.CharField(help_text='merge = dubblett, visas som en rad; boost = höjer ordningen.', max_length=10)),
                ('primary_external_id', models.TextField(db_index=True)),
                ('member_external_ids', models.JSONField(default=list)),
                ('boost', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('computed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'opportunity_combinations',
            },
        ),
    ]
