# Generated by Django 6.1.1 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_combinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePresence',
            fields=[
                ('device_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cell_lat', models.FloatField()),
                ('cell_lon', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'device_presence',
            },
        ),
    ]
