# Generated by Django 6.1.1 on 2026-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_device_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Väntar'), ('sending', 'Skickas'), ('sent', 'Skickad'), ('failed', 'Misslyckad'), ('expired', 'Utgången'), ('suppressed', 'Undertryckt (ingen åtkomst)')], default='sent', max_length=10),
        ),
    ]
