# Generated by Django 6.1.1 on 2026-09-30 17:45

from django.db import migrations, models

# Invariant 19, samma skäl som fleet/migrations/0003 och 0006: tabellen får
# inte nås via PostgREST, oavsett om Supabases default-privilegier är satta i
# miljön. Den är inte hemlig i sig -- samma värden står i /api/config -- men
# `authenticated` fick annars också SKRIVA, och då kunde vilken inloggad
# kund som helst låsa ute alla förare. Allt går via core/app_version.py.
REVOKE = """
do $$
declare
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if not exists (select 1 from pg_roles where rolname = r) then
      continue;
    end if;
    if to_regclass('public.app_version_policy') is not null then
      execute format('revoke all on table public.app_version_policy from %I', r);
    end if;
  end loop;
end $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_favorite_owner_is_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionPolicy',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('android_min_version', models.CharField(blank=True, default='', max_length=32)),
                ('android_recommended_version', models.CharField(blank=True, default='', max_length=32)),
                ('ios_min_version', models.CharField(blank=True, default='', max_length=32)),
                ('ios_recommended_version', models.CharField(blank=True, default='', max_length=32)),
                ('ios_store_url', models.CharField(blank=True, default='', max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_version_policy',
            },
        ),
        migrations.RunSQL(REVOKE, reverse_sql=migrations.RunSQL.noop),
    ]
